name: Generate Contributors

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run generator
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_README_PATH: README.md
          INPUT_COLUMNS_PER_ROW: '8'
          INPUT_IMAGE_SIZE: '100'
        run: |
          python ./.github/scripts/generate_contributors.py

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update contributors list [skip ci]'
          file_pattern: README.md
