name: Update Contributors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate Contributors List
        uses: akhilmhdh/contributors-readme-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "docs: update contributors"
          image_size: 100
          readme_path: README.md
          use_username: false
          columns_per_row: 6
          collaborators: direct
          auto_detect_branch_protection: true
          pr_title_on_protected: "docs(contributor): contributors readme action update"