name: Update Contributors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate Contributors List
        uses: akhilmhdh/contributors-readme-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "docs: update contributors"